// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coco-server/proto/monitor/monitor.proto

package monitor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// GoPsMemStatsResponse 内存状态请求参数
type GoPsMemStatsResponse struct {
	Alloc                string   `protobuf:"bytes,1,opt,name=Alloc,proto3" json:"Alloc,omitempty"`
	TotalAlloc           string   `protobuf:"bytes,2,opt,name=TotalAlloc,proto3" json:"TotalAlloc,omitempty"`
	Sys                  string   `protobuf:"bytes,3,opt,name=Sys,proto3" json:"Sys,omitempty"`
	Lookups              int64    `protobuf:"varint,4,opt,name=Lookups,proto3" json:"Lookups,omitempty"`
	Mallocs              int64    `protobuf:"varint,5,opt,name=Mallocs,proto3" json:"Mallocs,omitempty"`
	Frees                int64    `protobuf:"varint,6,opt,name=Frees,proto3" json:"Frees,omitempty"`
	HeapAlloc            string   `protobuf:"bytes,7,opt,name=HeapAlloc,proto3" json:"HeapAlloc,omitempty"`
	HeapSys              string   `protobuf:"bytes,8,opt,name=HeapSys,proto3" json:"HeapSys,omitempty"`
	HeapIdle             string   `protobuf:"bytes,9,opt,name=HeapIdle,proto3" json:"HeapIdle,omitempty"`
	HeapInUse            string   `protobuf:"bytes,10,opt,name=HeapInUse,proto3" json:"HeapInUse,omitempty"`
	HeapReleased         string   `protobuf:"bytes,11,opt,name=HeapReleased,proto3" json:"HeapReleased,omitempty"`
	HeapObjects          int64    `protobuf:"varint,12,opt,name=HeapObjects,proto3" json:"HeapObjects,omitempty"`
	StackInUse           string   `protobuf:"bytes,13,opt,name=StackInUse,proto3" json:"StackInUse,omitempty"`
	StackSys             string   `protobuf:"bytes,14,opt,name=StackSys,proto3" json:"StackSys,omitempty"`
	StackMspanInuse      string   `protobuf:"bytes,15,opt,name=StackMspanInuse,proto3" json:"StackMspanInuse,omitempty"`
	StackMspanSys        string   `protobuf:"bytes,16,opt,name=StackMspanSys,proto3" json:"StackMspanSys,omitempty"`
	StackMcacheInuse     string   `protobuf:"bytes,17,opt,name=StackMcacheInuse,proto3" json:"StackMcacheInuse,omitempty"`
	StackMcacheSys       string   `protobuf:"bytes,18,opt,name=StackMcacheSys,proto3" json:"StackMcacheSys,omitempty"`
	OtherSys             string   `protobuf:"bytes,19,opt,name=OtherSys,proto3" json:"OtherSys,omitempty"`
	GcSys                string   `protobuf:"bytes,20,opt,name=GcSys,proto3" json:"GcSys,omitempty"`
	NextGc               string   `protobuf:"bytes,21,opt,name=NextGc,proto3" json:"NextGc,omitempty"`
	LastGc               string   `protobuf:"bytes,22,opt,name=LastGc,proto3" json:"LastGc,omitempty"`
	GcPauseTotal         int64    `protobuf:"varint,23,opt,name=gcPauseTotal,proto3" json:"gcPauseTotal,omitempty"`
	GcPause              int64    `protobuf:"varint,24,opt,name=GcPause,proto3" json:"GcPause,omitempty"`
	GcPauseEnd           int64    `protobuf:"varint,25,opt,name=GcPauseEnd,proto3" json:"GcPauseEnd,omitempty"`
	NumGc                int64    `protobuf:"varint,26,opt,name=NumGc,proto3" json:"NumGc,omitempty"`
	NumForcedGc          int64    `protobuf:"varint,27,opt,name=NumForcedGc,proto3" json:"NumForcedGc,omitempty"`
	GcCpuFraction        float32  `protobuf:"fixed32,28,opt,name=GcCpuFraction,proto3" json:"GcCpuFraction,omitempty"`
	EnableGc             bool     `protobuf:"varint,29,opt,name=EnableGc,proto3" json:"EnableGc,omitempty"`
	DebugGc              bool     `protobuf:"varint,30,opt,name=DebugGc,proto3" json:"DebugGc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPsMemStatsResponse) Reset()         { *m = GoPsMemStatsResponse{} }
func (m *GoPsMemStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GoPsMemStatsResponse) ProtoMessage()    {}
func (*GoPsMemStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{1}
}

func (m *GoPsMemStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPsMemStatsResponse.Unmarshal(m, b)
}
func (m *GoPsMemStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPsMemStatsResponse.Marshal(b, m, deterministic)
}
func (m *GoPsMemStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPsMemStatsResponse.Merge(m, src)
}
func (m *GoPsMemStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GoPsMemStatsResponse.Size(m)
}
func (m *GoPsMemStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPsMemStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoPsMemStatsResponse proto.InternalMessageInfo

func (m *GoPsMemStatsResponse) GetAlloc() string {
	if m != nil {
		return m.Alloc
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetTotalAlloc() string {
	if m != nil {
		return m.TotalAlloc
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetSys() string {
	if m != nil {
		return m.Sys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetLookups() int64 {
	if m != nil {
		return m.Lookups
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetMallocs() int64 {
	if m != nil {
		return m.Mallocs
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetFrees() int64 {
	if m != nil {
		return m.Frees
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetHeapAlloc() string {
	if m != nil {
		return m.HeapAlloc
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetHeapSys() string {
	if m != nil {
		return m.HeapSys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetHeapIdle() string {
	if m != nil {
		return m.HeapIdle
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetHeapInUse() string {
	if m != nil {
		return m.HeapInUse
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetHeapReleased() string {
	if m != nil {
		return m.HeapReleased
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetHeapObjects() int64 {
	if m != nil {
		return m.HeapObjects
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetStackInUse() string {
	if m != nil {
		return m.StackInUse
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetStackSys() string {
	if m != nil {
		return m.StackSys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetStackMspanInuse() string {
	if m != nil {
		return m.StackMspanInuse
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetStackMspanSys() string {
	if m != nil {
		return m.StackMspanSys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetStackMcacheInuse() string {
	if m != nil {
		return m.StackMcacheInuse
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetStackMcacheSys() string {
	if m != nil {
		return m.StackMcacheSys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetOtherSys() string {
	if m != nil {
		return m.OtherSys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetGcSys() string {
	if m != nil {
		return m.GcSys
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetNextGc() string {
	if m != nil {
		return m.NextGc
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetLastGc() string {
	if m != nil {
		return m.LastGc
	}
	return ""
}

func (m *GoPsMemStatsResponse) GetGcPauseTotal() int64 {
	if m != nil {
		return m.GcPauseTotal
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetGcPause() int64 {
	if m != nil {
		return m.GcPause
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetGcPauseEnd() int64 {
	if m != nil {
		return m.GcPauseEnd
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetNumGc() int64 {
	if m != nil {
		return m.NumGc
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetNumForcedGc() int64 {
	if m != nil {
		return m.NumForcedGc
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetGcCpuFraction() float32 {
	if m != nil {
		return m.GcCpuFraction
	}
	return 0
}

func (m *GoPsMemStatsResponse) GetEnableGc() bool {
	if m != nil {
		return m.EnableGc
	}
	return false
}

func (m *GoPsMemStatsResponse) GetDebugGc() bool {
	if m != nil {
		return m.DebugGc
	}
	return false
}

type GoPsStatsResponse struct {
	Goroutines           int32    `protobuf:"varint,1,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	OSThreads            int32    `protobuf:"varint,2,opt,name=OSThreads,proto3" json:"OSThreads,omitempty"`
	GOMAXPROCS           int32    `protobuf:"varint,3,opt,name=GOMAXPROCS,proto3" json:"GOMAXPROCS,omitempty"`
	NumCPU               int32    `protobuf:"varint,4,opt,name=NumCPU,proto3" json:"NumCPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPsStatsResponse) Reset()         { *m = GoPsStatsResponse{} }
func (m *GoPsStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GoPsStatsResponse) ProtoMessage()    {}
func (*GoPsStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{2}
}

func (m *GoPsStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPsStatsResponse.Unmarshal(m, b)
}
func (m *GoPsStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPsStatsResponse.Marshal(b, m, deterministic)
}
func (m *GoPsStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPsStatsResponse.Merge(m, src)
}
func (m *GoPsStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GoPsStatsResponse.Size(m)
}
func (m *GoPsStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPsStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoPsStatsResponse proto.InternalMessageInfo

func (m *GoPsStatsResponse) GetGoroutines() int32 {
	if m != nil {
		return m.Goroutines
	}
	return 0
}

func (m *GoPsStatsResponse) GetOSThreads() int32 {
	if m != nil {
		return m.OSThreads
	}
	return 0
}

func (m *GoPsStatsResponse) GetGOMAXPROCS() int32 {
	if m != nil {
		return m.GOMAXPROCS
	}
	return 0
}

func (m *GoPsStatsResponse) GetNumCPU() int32 {
	if m != nil {
		return m.NumCPU
	}
	return 0
}

type GoPsStackResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPsStackResponse) Reset()         { *m = GoPsStackResponse{} }
func (m *GoPsStackResponse) String() string { return proto.CompactTextString(m) }
func (*GoPsStackResponse) ProtoMessage()    {}
func (*GoPsStackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{3}
}

func (m *GoPsStackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPsStackResponse.Unmarshal(m, b)
}
func (m *GoPsStackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPsStackResponse.Marshal(b, m, deterministic)
}
func (m *GoPsStackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPsStackResponse.Merge(m, src)
}
func (m *GoPsStackResponse) XXX_Size() int {
	return xxx_messageInfo_GoPsStackResponse.Size(m)
}
func (m *GoPsStackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPsStackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoPsStackResponse proto.InternalMessageInfo

func (m *GoPsStackResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// ProfilesRequest Profiles 请求参数
type GoPsProfilesRequest struct {
	Duration             int64    `protobuf:"varint,1,opt,name=Duration,proto3" json:"Duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPsProfilesRequest) Reset()         { *m = GoPsProfilesRequest{} }
func (m *GoPsProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*GoPsProfilesRequest) ProtoMessage()    {}
func (*GoPsProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{4}
}

func (m *GoPsProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPsProfilesRequest.Unmarshal(m, b)
}
func (m *GoPsProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPsProfilesRequest.Marshal(b, m, deterministic)
}
func (m *GoPsProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPsProfilesRequest.Merge(m, src)
}
func (m *GoPsProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_GoPsProfilesRequest.Size(m)
}
func (m *GoPsProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPsProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoPsProfilesRequest proto.InternalMessageInfo

func (m *GoPsProfilesRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// ProfilesResponse Profiles 返回参数
type GoPsProfilesResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPsProfilesResponse) Reset()         { *m = GoPsProfilesResponse{} }
func (m *GoPsProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*GoPsProfilesResponse) ProtoMessage()    {}
func (*GoPsProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{5}
}

func (m *GoPsProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPsProfilesResponse.Unmarshal(m, b)
}
func (m *GoPsProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPsProfilesResponse.Marshal(b, m, deterministic)
}
func (m *GoPsProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPsProfilesResponse.Merge(m, src)
}
func (m *GoPsProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_GoPsProfilesResponse.Size(m)
}
func (m *GoPsProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPsProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoPsProfilesResponse proto.InternalMessageInfo

func (m *GoPsProfilesResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type GoPsBinaryResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPsBinaryResponse) Reset()         { *m = GoPsBinaryResponse{} }
func (m *GoPsBinaryResponse) String() string { return proto.CompactTextString(m) }
func (*GoPsBinaryResponse) ProtoMessage()    {}
func (*GoPsBinaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9dc954418dbbba6, []int{6}
}

func (m *GoPsBinaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPsBinaryResponse.Unmarshal(m, b)
}
func (m *GoPsBinaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPsBinaryResponse.Marshal(b, m, deterministic)
}
func (m *GoPsBinaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPsBinaryResponse.Merge(m, src)
}
func (m *GoPsBinaryResponse) XXX_Size() int {
	return xxx_messageInfo_GoPsBinaryResponse.Size(m)
}
func (m *GoPsBinaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPsBinaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoPsBinaryResponse proto.InternalMessageInfo

func (m *GoPsBinaryResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "monitor.Empty")
	proto.RegisterType((*GoPsMemStatsResponse)(nil), "monitor.GoPsMemStatsResponse")
	proto.RegisterType((*GoPsStatsResponse)(nil), "monitor.GoPsStatsResponse")
	proto.RegisterType((*GoPsStackResponse)(nil), "monitor.GoPsStackResponse")
	proto.RegisterType((*GoPsProfilesRequest)(nil), "monitor.GoPsProfilesRequest")
	proto.RegisterType((*GoPsProfilesResponse)(nil), "monitor.GoPsProfilesResponse")
	proto.RegisterType((*GoPsBinaryResponse)(nil), "monitor.GoPsBinaryResponse")
}

func init() {
	proto.RegisterFile("coco-server/proto/monitor/monitor.proto", fileDescriptor_a9dc954418dbbba6)
}

var fileDescriptor_a9dc954418dbbba6 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0xc7, 0x15, 0x52, 0x93, 0x70, 0xf8, 0x1e, 0x28, 0x9d, 0x86, 0x0f, 0x45, 0x16, 0x6a, 0xa3,
	0x4a, 0x40, 0x5b, 0xa4, 0x4a, 0x5c, 0xf4, 0x82, 0x06, 0x70, 0xa9, 0x08, 0x89, 0x1c, 0x90, 0x7a,
	0x3b, 0x99, 0x4c, 0x21, 0x25, 0xf1, 0x78, 0x3d, 0xe3, 0xd5, 0xf2, 0x08, 0x7b, 0xbf, 0x4f, 0xb6,
	0x4f, 0xb4, 0x3a, 0x67, 0xe2, 0xc4, 0x8e, 0xa5, 0x45, 0x7b, 0x85, 0x7f, 0xff, 0xf3, 0xc9, 0x39,
	0x33, 0x13, 0xf8, 0x59, 0x6a, 0xa9, 0x4f, 0x8c, 0x4a, 0xde, 0xab, 0xe4, 0x2c, 0x4e, 0xb4, 0xd5,
	0x67, 0x13, 0x1d, 0x8d, 0xac, 0x4e, 0xb2, 0xbf, 0xa7, 0xa4, 0xb2, 0xda, 0x14, 0xfd, 0x1a, 0x78,
	0xd7, 0x93, 0xd8, 0xbe, 0xfa, 0x9f, 0x6a, 0xb0, 0x1b, 0xe8, 0x9e, 0xe9, 0xa8, 0x49, 0xdf, 0x0a,
	0x6b, 0x42, 0x65, 0x62, 0x1d, 0x19, 0xc5, 0x76, 0xc1, 0xbb, 0x1c, 0x8f, 0xb5, 0xe4, 0x95, 0x66,
	0xa5, 0xb5, 0x12, 0x3a, 0x60, 0x47, 0x00, 0x0f, 0xda, 0x8a, 0xb1, 0x33, 0x2d, 0x91, 0x29, 0xa7,
	0xb0, 0x2d, 0xa8, 0xf6, 0x5f, 0x0d, 0xaf, 0x92, 0x01, 0x3f, 0x19, 0x87, 0xda, 0x9d, 0xd6, 0x2f,
	0x69, 0x6c, 0xf8, 0x77, 0xcd, 0x4a, 0xab, 0x1a, 0x66, 0x88, 0x96, 0x8e, 0xc0, 0x28, 0xc3, 0x3d,
	0x67, 0x99, 0x22, 0xd6, 0xbe, 0x49, 0x94, 0x32, 0x7c, 0x99, 0x74, 0x07, 0xec, 0x00, 0x56, 0xfe,
	0x56, 0x22, 0x76, 0xa5, 0x6b, 0x54, 0x61, 0x2e, 0x60, 0x36, 0x04, 0xac, 0x5e, 0x27, 0x5b, 0x86,
	0xac, 0x01, 0x75, 0xfc, 0xbc, 0x1d, 0x8e, 0x15, 0x5f, 0x21, 0xd3, 0x8c, 0xb3, 0x9c, 0xb7, 0xd1,
	0xa3, 0x51, 0x1c, 0xe6, 0x39, 0x49, 0x60, 0x3e, 0xac, 0x21, 0x84, 0x6a, 0xac, 0x84, 0x51, 0x43,
	0xbe, 0x4a, 0x0e, 0x05, 0x8d, 0x35, 0x61, 0x15, 0xb9, 0x3b, 0xf8, 0x5f, 0x49, 0x6b, 0xf8, 0x1a,
	0x75, 0x9c, 0x97, 0x70, 0x66, 0x7d, 0x2b, 0xe4, 0x8b, 0x2b, 0xb2, 0xee, 0x66, 0x36, 0x57, 0xb0,
	0x3f, 0x22, 0x6c, 0x7d, 0xc3, 0xf5, 0x97, 0x31, 0x6b, 0xc1, 0x26, 0x7d, 0x77, 0x4c, 0x2c, 0xa2,
	0xdb, 0x28, 0x35, 0x8a, 0x6f, 0x92, 0xcb, 0xa2, 0xcc, 0x8e, 0x61, 0x7d, 0x2e, 0x61, 0xaa, 0x2d,
	0xf2, 0x2b, 0x8a, 0xec, 0x17, 0xd8, 0x72, 0x82, 0x14, 0xf2, 0x59, 0xb9, 0x84, 0xdb, 0xe4, 0x58,
	0xd2, 0xd9, 0x4f, 0xb0, 0x91, 0xd3, 0x30, 0x25, 0x23, 0xcf, 0x05, 0x15, 0xfb, 0xef, 0xda, 0x67,
	0x95, 0xa0, 0xc7, 0x8e, 0xeb, 0x3f, 0x63, 0xdc, 0x64, 0x20, 0xd1, 0xb0, 0xeb, 0x4e, 0x11, 0x01,
	0xdb, 0x83, 0xe5, 0x7b, 0xf5, 0xc1, 0x06, 0x92, 0x7f, 0x4f, 0xf2, 0x94, 0x50, 0xbf, 0x13, 0x06,
	0xf5, 0x3d, 0xa7, 0x3b, 0xc2, 0x3d, 0x3c, 0xc9, 0x9e, 0x48, 0x8d, 0xa2, 0xa3, 0xc6, 0x7f, 0xa0,
	0x21, 0x17, 0x34, 0xdc, 0x7f, 0xe0, 0x98, 0x73, 0x77, 0x9a, 0xa6, 0x88, 0xf3, 0x9f, 0x7e, 0x5e,
	0x47, 0x43, 0xfe, 0x23, 0x19, 0x73, 0x0a, 0xf6, 0x78, 0x9f, 0x4e, 0x02, 0xc9, 0x1b, 0xee, 0xb4,
	0x11, 0xe0, 0x5e, 0xef, 0xd3, 0xc9, 0x8d, 0x4e, 0xa4, 0x1a, 0x06, 0x92, 0xef, 0xbb, 0xbd, 0xe6,
	0x24, 0x9c, 0x78, 0x20, 0xdb, 0x71, 0x7a, 0x93, 0x08, 0x69, 0x47, 0x3a, 0xe2, 0x07, 0xcd, 0x4a,
	0x6b, 0x29, 0x2c, 0x8a, 0x38, 0x9d, 0xeb, 0x48, 0x0c, 0xc6, 0x2a, 0x90, 0xfc, 0xb0, 0x59, 0x69,
	0xd5, 0xc3, 0x19, 0x63, 0xcf, 0x57, 0x6a, 0x90, 0x3e, 0x05, 0x92, 0x1f, 0x91, 0x29, 0x43, 0xff,
	0x63, 0x05, 0xb6, 0xf1, 0x5a, 0x16, 0xef, 0xe4, 0x11, 0xc0, 0x93, 0x4e, 0x74, 0x6a, 0x47, 0x91,
	0x32, 0x74, 0x31, 0xbd, 0x30, 0xa7, 0xe0, 0x69, 0xee, 0xf6, 0x1f, 0x9e, 0x13, 0x25, 0x86, 0x86,
	0x2e, 0xa7, 0x17, 0xce, 0x05, 0x9a, 0x43, 0xb7, 0x73, 0xf9, 0x6f, 0x2f, 0xec, 0xb6, 0xfb, 0x74,
	0x45, 0xbd, 0x30, 0xa7, 0xd0, 0x56, 0xd2, 0x49, 0xbb, 0xf7, 0x48, 0x17, 0xd5, 0x0b, 0xa7, 0xe4,
	0x9f, 0xcc, 0x5a, 0x91, 0x2f, 0xb3, 0x56, 0x38, 0xd4, 0xa4, 0x8e, 0xac, 0x8a, 0x2c, 0xf5, 0xb1,
	0x16, 0x66, 0xe8, 0xff, 0x06, 0x3b, 0xe8, 0xde, 0x4b, 0xf4, 0x7f, 0xa3, 0xb1, 0x32, 0xa1, 0x7a,
	0x97, 0x2a, 0x63, 0x71, 0x0e, 0x57, 0x69, 0x22, 0x68, 0x50, 0x15, 0x1a, 0xe6, 0x8c, 0xfd, 0x5f,
	0xdd, 0x1b, 0x34, 0x0f, 0x99, 0x17, 0x69, 0x17, 0x8b, 0x4c, 0xd1, 0x3f, 0x05, 0x86, 0x11, 0x7f,
	0x8d, 0x22, 0x91, 0xbc, 0xbe, 0xed, 0xff, 0xfb, 0xe7, 0x2a, 0xd4, 0x3a, 0xee, 0xed, 0x63, 0xc7,
	0xb0, 0x14, 0xb4, 0xd9, 0xc6, 0x69, 0xf6, 0x34, 0xd2, 0x43, 0xd8, 0x58, 0x60, 0x76, 0x0e, 0x1e,
	0xfd, 0xc7, 0x25, 0xc7, 0xc6, 0x8c, 0xcb, 0x53, 0x71, 0x41, 0xd6, 0xbc, 0x1d, 0x94, 0xdb, 0xea,
	0x05, 0xd4, 0xb3, 0xd7, 0xb7, 0x14, 0x77, 0x58, 0x88, 0x2b, 0x3d, 0xd2, 0xff, 0xc0, 0x6a, 0x3b,
	0x4e, 0xb3, 0xb9, 0xb1, 0x83, 0x82, 0xf7, 0xc2, 0x06, 0x16, 0x72, 0x95, 0x86, 0xfd, 0xa7, 0x7b,
	0xec, 0x66, 0xc9, 0xbe, 0xde, 0x4a, 0x29, 0xfc, 0x02, 0xc0, 0x6d, 0xe3, 0x2a, 0x9d, 0xc4, 0xa5,
	0xe0, 0xfd, 0x42, 0xf0, 0xc2, 0xda, 0xfe, 0x00, 0xef, 0x21, 0x11, 0x52, 0x7d, 0x63, 0xc9, 0xc1,
	0x32, 0xfd, 0xa8, 0x9d, 0x7f, 0x09, 0x00, 0x00, 0xff, 0xff, 0x47, 0x70, 0x77, 0x14, 0xff, 0x06,
	0x00, 0x00,
}
